### PR TITLE
Remove tag throws error when tags do not exist in the person

### LINKED ISSUE #127: [SUGGESTION] Removing a non-existent tag should throw an error
### How to reproduce
1. Remove a non-existent tag from an existing user
2. There will be no response from the app, except that the access count to the user increased

### Screenshot
image

### PR DESCRIPTION
**Pull request by kenpaxtonlim**
Fixes #127

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddRemoveTagsCommand.java [hunk 1]
```diff
@@ -122,11 +124,28 @@ private static Person addTagsToPerson(ReadOnlyPerson personToEdit, Set<Tag> tags
...
+            if (!personTags.contains(t)) {
+                doesTagsExist = false;
+                dontExist.add(t);
+            }
+        }
+
+        if (!doesTagsExist) {
+            String message = MESSAGE_TAG_DONT_EXIST;
+            for (Tag t: dontExist) {
+                message += " " + t.tagName;
```
Comment (donjar) [inline src/main/java/seedu/address/logic/commands/AddRemoveTagsCommand.java]: Use a `StringBuilder` instead for better performance

Comment (donjar) [reply src/main/java/seedu/address/logic/commands/AddRemoveTagsCommand.java]: Or actually, maybe abstract this to a method that takes a varargs of Strings and returns the full message? I think can use `String#join` as well: https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.CharSequence...-

File: src/test/java/seedu/address/logic/commands/AddRemoveTagsCommandTest.java [hunk 2]
```diff
@@ -78,6 +78,26 @@ public void execute_removeTags_success() throws Exception {
...
+
+        AddRemoveTagsCommand removeTagsCommand = prepareCommandRemove(INDEX_FIRST_PERSON,
+                ParserUtil.parseTags(tagsList));
+
+        Model expectedModel = new ModelManager(new AddressBook(model.getAddressBook()),
+                new UserPrefs());
+        expectedModel.updatePerson(model.getFilteredPersonList().get(0), editedPerson);
+
+        assertCommandFailure(removeTagsCommand, model,
+                AddRemoveTagsCommand.MESSAGE_TAG_DONT_EXIST + " husband");
```
Comment (donjar) [inline src/test/java/seedu/address/logic/commands/AddRemoveTagsCommandTest.java]: Then this one can be abstracted away as well.

File: src/test/java/seedu/address/logic/commands/AddRemoveTagsCommandTest.java [hunk 3]
```diff
@@ -78,6 +78,26 @@ public void execute_removeTags_success() throws Exception {
...
+        ArrayList<String> tagsList = new ArrayList<>();
+        tagsList.add("friends");
+        tagsList.add("husband");
+
+        AddRemoveTagsCommand removeTagsCommand = prepareCommandRemove(INDEX_FIRST_PERSON,
+                ParserUtil.parseTags(tagsList));
+
+        Model expectedModel = new ModelManager(new AddressBook(model.getAddressBook()),
+                new UserPrefs());
+        expectedModel.updatePerson(model.getFilteredPersonList().get(0), editedPerson);
```
Comment (donjar) [inline src/test/java/seedu/address/logic/commands/AddRemoveTagsCommandTest.java]: I think the 0 here should be `INDEX_FIRST_PERSON.getZeroBased()`

**Review by donjar — APPROVED** [review]
